### ISSUE TITLE
Camera view?

### ISSUE THREAD

**Issue by ecentinela** [bushvin/hass_chitubox_printer#2]
Hi!

Not an issue, but a question I don't know where to publish.

Is it possible to include the camera view as we see in the Chitubox Manager application?

Thanks!

**Comment by bushvin** [comment]
Yeah, I was going to work on that, but I haven't found the time yet... Not to print, nor to code...

**Comment by bushvin** [comment]
@ecentinela I did some investigation, and it seems the rtsp stream provided by the device is wonky, which is not really good for ffmpeg (which is used to stream rtsp)...

I couldn't get it to work with the ffmpeg integration, but `ffplay` was kind of ok:
`ffplay -vf "setpts=1/60*PTS" rtsp://<ip of saturn>:554/video` was working

```yml
camera:
  - platform: ffmpeg
    name: test
    input: rtsp://<ip of saturn>:554/video
    extra_arguments: >-
      -vf "setpts=1/60*PTS" -an
```
causing

`2025-03-30 13:35:12.643 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.test] Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input, rtsp://<ip of saturn>:554/video)`

So for now, no camera... I will see to raise an issue and see what gives.

I was thinking of generating a screenshot, like a timelapse, but the Saturn 4 is limited to 2 streams, so after 2 pics, you wouldn't get any more... :(
